### ISSUE TITLE
Unskip tests in TravisCI

### ISSUE THREAD

**Issue by indexzero** [godaddy/warehouse.ai#22]
Currently we have decent integration test coverage, but the necessary configuration for remote services (like S3) is not stored anywhere securely – only local machines. We need to integrate this configuration with TravisCI and unskip those integration tests.

**Comment by msluther** [comment]
Secure configuration has been added and integration tests were re-enabled by this [PR](https://github.com/godaddy/warehouse.ai/pull/24)
