### ISSUE TITLE
Ignore garbage files (i.e. non-whitelisted) BEFORE minification

### ISSUE THREAD

**Issue by laurenelee** [godaddy/warehouse.ai#34]
Feature area: Warehouse

Currently the non-ignored files are also minified and then ignored. This is a minor amount of CPU time wasted, but ideally we would ignore those files before we minify them.

**Comment by Swaagie** [comment]
Good callout, filter before minify.

**Comment by JacopoDaeli** [comment]
I think we do not need this anymore, therefore closing it now. Happy to reopen if this matter or similar comes back again.
