### ISSUE TITLE
Create postman config for warehouse.ai endpoints with minor cleanup

### ISSUE THREAD

**Issue by laurenelee** [godaddy/warehouse.ai#35]
This ticket is meant to follow the `app-data-service` example and create open source configuration for postman for the https://github.com/godaddy/warehouse.ai project. In this context we should also remove any endpoints that our no longer used from the carpenter refactor. An example is that carpenter builds cannot be cancelled so this route should be removed from warehouse.ai as well.

Acceptance Criteria:

Add postman config for viable routes in warehouse.ai repo
While confirming dependent/proxy routes in carpenter do not exist, remove the routes in warehouse.ai code.
Update the README.md in warehouse.ai to remove any routes that dont actually exist.

**Comment by JacopoDaeli** [comment]
Closing this since new version of Warehouse expose Swagger endpoints.
