### ISSUE TITLE
Create an ability to control my warehouse.ai file ordering

### ISSUE THREAD

**Issue by laurenelee** [godaddy/warehouse.ai#36]
Acceptance Criteria:

File ordering when warehouse.ai returns a build is returned in the same order as the files are defined in wrhs.toml
e.g. if I've defined
`prod = ['dist/zoo.min.js', 'dist/anotherFile.min.js']`
Then when wrhs returns the files, zoo.min.js should always be returned first in the array of files followed by anotherFile.min.js.

**Comment by JacopoDaeli** [comment]
Closing this since the concept of wrhs.toml is gone in the new version of Warehouse.
