### ISSUE TITLE
Create a warehouse configuration doc

### ISSUE THREAD

**Issue by msluther** [godaddy/warehouse.ai#46]
Acceptance Criteria:
- Separate doc in https://github.com/godaddy/warehouse.ai covering:
      - Covers how to configure a package to be built, pull docs from the new
      config repo
      - What builds types are supported with any caveats (e.g. webpack.config must
      be in root of package, must output to dist-directory, etc).
      - Locale support, build output, build type, etc.
      - How to consume build parameters (locale, etc?) from your build system
      (webpack.config, browserify, babel?)

**Comment by JacopoDaeli** [comment]
Closing this since warehouse next has much simpler configuration.
