### ISSUE TITLE
Tests fail with localstack >= 0.11.4

### ISSUE THREAD

**Issue by decompil3d** [godaddy/warehouse.ai#93]
## 🐛 Bug Report

Tests fail with `localstack` >= 0.11.4

## To Reproduce

1. Pull `localstack` 0.11.4 or later

```sh
docker pull localstack/localstack:latest
```

2. Run tests

```sh
npm test
```

## Expected Behavior

Tests pass

## Actual Behavior

Tests fail

## Environment

Mac OS 10.15.6, Node 12

**Comment by msluther** [comment]
IIRC the issue with newer `localstack`s is just that they went with a single port for all services rather than a port per service type. Should be a straightforward fix to be able to use latest.

**Comment by msluther** [comment]
<https://github.com/localstack/localstack#overview>

> **Note:** Starting with version `0.11.0`, all APIs are exposed via a single _edge service_, which is accessible on http://localhost:4566 by default (customizable via `EDGE_PORT`, see further below).

We should just be able to update to use that other port and keep on with whatever the latest `localstack` is (which has some nice docker image size fixes)

**Comment by decompil3d** [comment]
I did that fix in #94. Did not work. There's something screwy going on with DynamoDB in those later versions. Getting lots of  "Table already exists" errors.

**Comment by decompil3d** [comment]
Since we're pinned at 0.11.3, I was able to just leave the port change there so we're ready for the update. Just need to determine the cause of those test errors.

**Comment by JacopoDaeli** [comment]
@decompil3d do we still want to look into this now that we're about to release wrhs 7.x?

**Comment by decompil3d** [comment]
It's fair to close these issues after `7.x` merges into `master`.
